
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
Epoch Done
[INFO] Not enough data, proceeding...
0.13343361485749483 0.7374116461724043
Traceback (most recent call last):
  File "/data_hdd1/hassan/projects/GPS/eval.py", line 102, in <module>
    plt.plot(px, py)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2840, in plot
    return gca().plot(
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2368, in gca
    return gcf().gca(**kwargs)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/pyplot.py", line 747, in gcf
    return figure()
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/pyplot.py", line 693, in figure
    **kwargs)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 901, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure, master=window)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 187, in __init__
    self._tkcanvas.create_image(w//2, h//2, image=self._tkphoto)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/tkinter/__init__.py", line 2489, in create_image
    return self._create('image', args, kw)
  File "/home/user01/anaconda3/envs/pt/lib/python3.6/tkinter/__init__.py", line 2480, in _create
    *(args + self._options(cnf, kw))))
KeyboardInterrupt